apiVersion: v1
kind: Namespace
metadata:
  name: mar
  labels:
    environment-id: env_b6991151-288f-4172-99ea-d1301b3c5477
    project-id: project_e50f311a-e15b-4fe7-a101-1c407328e0e6
    project-name: dogHouse0435
    environment-name: staging
    organization-id: org_01b50229-db34-43d4-8f3e-d1aeb683d900
